"""
ScopeSynth Lead Intake Agent — Multi-Tenant Edition
LangGraph-powered SDR qualifying agent using Google Gemini 2.5 Flash
Company name & sector are fully configurable — no hardcoded branding.
"""
import os
import json
import uuid
import re
import logging
from typing import Annotated
from typing_extensions import TypedDict
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.middleware.cors import CORSMiddleware
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages
import uvicorn
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# ── Logging ──────────────────────────────────────────────────────────────────
log_dir = Path(__file__).parent.parent / "logs"
log_dir.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    handlers=[
        logging.FileHandler(log_dir / "lead-intake.json"),
        logging.StreamHandler()
    ],
    format='{"time":"%(asctime)s","level":"%(levelname)s","msg":"%(message)s"}'
)
logger = logging.getLogger("lead-intake")

# ── LangGraph State ───────────────────────────────────────────────────────────
class LeadState(TypedDict):
    messages:    Annotated[list, add_messages]
    stage:       str    # greet | project | budget | email | summary | done
    lead_data:   dict   # accumulated lead info
    company:     str    # configurable company name
    sector:      str    # configurable industry / sector
    agent_name:  str    # configurable SDR agent name

# ── LLM ──────────────────────────────────────────────────────────────────────
def get_llm():
    return ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        google_api_key=os.getenv("GEMINI_API_KEY", ""),
        temperature=0.7,
    )

# ── Dynamic System Prompt ─────────────────────────────────────────────────────
def build_system_prompt(company: str, sector: str, agent_name: str) -> str:
    return f"""You are {agent_name}, a senior SDR (Sales Development Representative) for {company} —
a company in the {sector} sector. You are professional, warm, and consultative.
You qualify leads efficiently through a structured conversation.
Keep responses concise (2-4 sentences max). Be conversational, not robotic.
Always represent the {company} brand professionally and adapt your language to the {sector} industry context."""

# ── Stage Instructions ────────────────────────────────────────────────────────
def build_stage_instructions(stage: str, company: str, sector: str,
                              agent_name: str, lead_data: dict) -> str:
    return {
        "greet": (
            f"Greet the user warmly. Introduce yourself as {agent_name} from {company}. "
            f"Briefly mention that {company} operates in the {sector} space. "
            f"Ask them what type of project or requirement they have in mind."
        ),
        "project": (
            f"The user shared their project or requirement. Acknowledge it with genuine enthusiasm "
            f"relevant to the {sector} sector. Ask about their budget range and timeline."
        ),
        "budget": (
            f"Acknowledge their budget and timeline thoughtfully. "
            f"Ask for their business email so {company} can send a tailored proposal."
        ),
        "email": (
            f"Thank them warmly for their email. Let them know {company} will follow up. "
            f"Tell them you're generating their lead summary now."
        ),
        "summary": f"""Generate a professional Lead Summary report in this EXACT format:

---
🎯 LEAD SUMMARY — {company}
━━━━━━━━━━━━━━━━━━━━━━━━
🏢 Company: {company}
🏭 Sector: {sector}
👤 Contact Email: {lead_data.get('email', 'N/A')}
🏗️ Project / Requirement: {lead_data.get('project_type', 'N/A')}
💰 Budget Range: {lead_data.get('budget', 'N/A')}
⏱️ Timeline: {lead_data.get('timeline', 'N/A')}
📊 Lead Score: [Rate 1-10 based on budget clarity and project fit for {sector}]
🔥 Priority: [Hot/Warm/Cool]
📝 Notes: [2-3 sentence assessment tailored to the {sector} context]
✅ Next Action: [Specific next step for {company}]
━━━━━━━━━━━━━━━━━━━━━━━━
Generated by ScopeSynth Lead Intake | {company}
---
End with: "Thank you! The {company} team will reach out within 24 hours." """,
    }.get(stage, "Continue the conversation helpfully.")

# ── Agent Node ────────────────────────────────────────────────────────────────
def agent_node(state: LeadState) -> LeadState:
    llm        = get_llm()
    stage      = state["stage"]
    company    = state.get("company",    "Our Company")
    sector     = state.get("sector",     "Technology")
    agent_name = state.get("agent_name", "Alex")
    lead_data  = state["lead_data"]

    system_prompt = build_system_prompt(company, sector, agent_name)
    instruction   = build_stage_instructions(stage, company, sector, agent_name, lead_data)

    messages_to_send = (
        [SystemMessage(content=f"{system_prompt}\n\nCURRENT TASK: {instruction}")]
        + list(state["messages"])
    )
    response = llm.invoke(messages_to_send)
    logger.info(f"stage={stage} company={company} sector={sector}")
    return {**state, "messages": [AIMessage(content=response.content)]}

# ── Extract Info Node ─────────────────────────────────────────────────────────
def extract_info_node(state: LeadState) -> LeadState:
    llm       = get_llm()
    stage     = state["stage"]
    lead_data = dict(state["lead_data"])

    last_human = next(
        (m.content for m in reversed(state["messages"]) if isinstance(m, HumanMessage)), ""
    )

    if stage == "project" and last_human:
        result = llm.invoke([HumanMessage(content=(
            f'Extract the project type or requirement from: "{last_human}"\n'
            f'Return ONLY JSON: {{"project_type": "extracted value"}}'
        ))])
        try:
            clean = result.content.strip().replace("```json","").replace("```","")
            lead_data.update(json.loads(clean))
        except Exception:
            lead_data["project_type"] = last_human[:120]

    elif stage == "budget" and last_human:
        result = llm.invoke([HumanMessage(content=(
            f'Extract budget range and timeline from: "{last_human}"\n'
            f'Return ONLY JSON: {{"budget": "value", "timeline": "value"}}'
        ))])
        try:
            clean = result.content.strip().replace("```json","").replace("```","")
            lead_data.update(json.loads(clean))
        except Exception:
            lead_data["budget"] = last_human[:120]

    elif stage == "email" and last_human:
        match = re.search(r'[\w.+-]+@[\w-]+\.[a-zA-Z]+', last_human)
        lead_data["email"] = match.group(0) if match else last_human.strip()

    return {**state, "lead_data": lead_data}

# ── Stage Transitions ─────────────────────────────────────────────────────────
STAGE_MAP = {
    "greet":   "project",
    "project": "budget",
    "budget":  "email",
    "email":   "summary",
    "summary": "done",
}

# ── Build LangGraph ───────────────────────────────────────────────────────────
def build_graph():
    g = StateGraph(LeadState)
    g.add_node("agent",   agent_node)
    g.add_node("extract", extract_info_node)
    g.set_entry_point("agent")
    g.add_edge("extract", "agent")
    g.add_edge("agent",   END)
    return g.compile()

compiled_graph = build_graph()

# ── Session Store ─────────────────────────────────────────────────────────────
sessions: dict[str, LeadState] = {}

def get_or_create_session(session_id: str, company: str, sector: str,
                           agent_name: str) -> LeadState:
    if session_id not in sessions:
        sessions[session_id] = {
            "messages":   [],
            "stage":      "greet",
            "lead_data":  {},
            "company":    company,
            "sector":     sector,
            "agent_name": agent_name,
        }
    return sessions[session_id]

def process_message(session_id: str, company: str, sector: str,
                    agent_name: str, user_input: str | None = None) -> str:
    state = get_or_create_session(session_id, company, sector, agent_name)

    if user_input:
        state["messages"] = list(state["messages"]) + [HumanMessage(content=user_input)]
        if state["stage"] in ["project", "budget", "email"]:
            state = extract_info_node(state)

    result      = agent_node(state)
    ai_response = result["messages"][-1].content
    next_stage  = STAGE_MAP.get(state["stage"], "done")

    state["messages"]  = list(state["messages"]) + [AIMessage(content=ai_response)]
    state["stage"]     = next_stage
    state["lead_data"] = result["lead_data"]
    sessions[session_id] = state

    logger.info(f"session={session_id} new_stage={next_stage} company={company}")
    return ai_response

# ── FastAPI ───────────────────────────────────────────────────────────────────
app = FastAPI(title="ScopeSynth Lead Intake")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

# ── HTML Template (logo initials + company/sector injected at runtime) ─────────
HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title id="page-title">Lead Intake Agent</title>
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{background:#0f172a;color:#e2e8f0;font-family:'Segoe UI',system-ui,sans-serif;height:100vh;display:flex;flex-direction:column}

  /* Config Modal */
  .modal-overlay{position:fixed;inset:0;background:#00000090;z-index:200;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(4px)}
  .modal{background:#1e293b;border:1px solid #334155;border-radius:16px;padding:32px;width:460px;max-width:92vw;display:flex;flex-direction:column;gap:18px}
  .modal h2{font-size:18px;font-weight:800;color:#f1f5f9;display:flex;align-items:center;gap:10px}
  .modal p{font-size:13px;color:#94a3b8;line-height:1.6}
  .modal label{font-size:12px;color:#94a3b8;display:block;margin-bottom:5px;font-weight:600;text-transform:uppercase;letter-spacing:.6px}
  .modal input,.modal select{width:100%;background:#0f172a;border:1px solid #334155;border-radius:8px;padding:10px 14px;color:#e2e8f0;font-size:14px;outline:none;transition:border .2s}
  .modal input:focus,.modal select:focus{border-color:#e11d48}
  .modal input::placeholder{color:#475569}
  .modal-btn{background:#e11d48;color:#fff;border:none;border-radius:10px;padding:12px;font-size:14px;font-weight:700;cursor:pointer;width:100%;transition:background .2s}
  .modal-btn:hover{background:#be123c}
  .modal-hint{font-size:11px;color:#475569;text-align:center}

  /* Header */
  header{background:#1e293b;border-bottom:1px solid #334155;padding:14px 22px;display:flex;align-items:center;gap:12px;flex-shrink:0}
  .logo{width:36px;height:36px;background:#e11d48;border-radius:8px;display:flex;align-items:center;justify-content:center;font-weight:800;font-size:13px;color:#fff;flex-shrink:0}
  .header-text h1{font-size:16px;font-weight:700;color:#f1f5f9;line-height:1.2}
  .header-text .sub{font-size:11px;color:#94a3b8;margin-top:2px}
  .header-right{margin-left:auto;display:flex;align-items:center;gap:8px}
  .badge{background:#e11d4818;color:#e11d48;border:1px solid #e11d4830;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600}
  .sector-pill{background:#7c3aed18;color:#a78bfa;border:1px solid #7c3aed30;padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600}
  .config-btn{background:transparent;border:1px solid #334155;color:#94a3b8;border-radius:8px;padding:5px 12px;font-size:12px;cursor:pointer;transition:all .2s}
  .config-btn:hover{border-color:#e11d48;color:#e11d48}

  /* Chat */
  #chat{flex:1;overflow-y:auto;padding:24px;display:flex;flex-direction:column;gap:16px}
  .msg{display:flex;gap:10px;max-width:680px}
  .msg.user{flex-direction:row-reverse;margin-left:auto}
  .avatar{width:34px;height:34px;border-radius:50%;flex-shrink:0;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700}
  .msg.agent .avatar{background:#e11d48;color:#fff}
  .msg.user .avatar{background:#334155;color:#94a3b8}
  .bubble{background:#1e293b;border:1px solid #334155;border-radius:12px;padding:13px 16px;font-size:14px;line-height:1.7;max-width:560px;white-space:pre-wrap}
  .msg.user .bubble{background:#1e3a5f;border-color:#1e40af;text-align:right}
  .typing{display:flex;gap:6px;padding:13px 16px;background:#1e293b;border:1px solid #334155;border-radius:12px;width:fit-content}
  .typing span{width:7px;height:7px;background:#e11d48;border-radius:50%;animation:bounce 1.2s infinite}
  .typing span:nth-child(2){animation-delay:.2s}
  .typing span:nth-child(3){animation-delay:.4s}
  @keyframes bounce{0%,80%,100%{transform:translateY(0)}40%{transform:translateY(-8px)}}
  .done-banner{background:#0f2e1a;border:1px solid #16a34a;color:#86efac;padding:12px 16px;border-radius:10px;font-size:13px;text-align:center}

  /* Footer */
  .chat-footer{background:#1e293b;border-top:1px solid #334155;padding:14px 22px;display:flex;gap:10px;flex-shrink:0}
  #msg-input{flex:1;background:#0f172a;border:1px solid #334155;border-radius:10px;padding:11px 14px;color:#e2e8f0;font-size:14px;outline:none;transition:border .2s}
  #msg-input:focus{border-color:#e11d48}
  #msg-input::placeholder{color:#475569}
  #send-btn{background:#e11d48;color:#fff;border:none;border-radius:10px;padding:11px 22px;font-size:14px;font-weight:600;cursor:pointer;transition:background .2s}
  #send-btn:hover{background:#be123c}
  #send-btn:disabled{background:#334155;color:#64748b;cursor:not-allowed}
</style>
</head>
<body>

<!-- ── Config Modal ──────────────────────────────────────── -->
<div class="modal-overlay" id="config-modal">
  <div class="modal">
    <h2>⚙️ Configure Lead Intake Agent</h2>
    <p>Set the company and sector for this intake session. These can also be passed via URL params: <code style="color:#e11d48">?company=Acme&amp;sector=Healthcare&amp;agent=Alex</code></p>
    <div>
      <label>Company / Organisation Name</label>
      <input type="text" id="cfg-company" placeholder="e.g. Acme Corp, Fi Techs, MedGrove…" maxlength="80"/>
    </div>
    <div>
      <label>Industry / Sector</label>
      <select id="cfg-sector">
        <option value="">— Select a sector —</option>
        <option value="AI &amp; Software Agency">AI &amp; Software Agency</option>
        <option value="Healthcare &amp; MedTech">Healthcare &amp; MedTech</option>
        <option value="FinTech &amp; Banking">FinTech &amp; Banking</option>
        <option value="E-Commerce &amp; Retail">E-Commerce &amp; Retail</option>
        <option value="EdTech &amp; Learning">EdTech &amp; Learning</option>
        <option value="Real Estate &amp; PropTech">Real Estate &amp; PropTech</option>
        <option value="Legal &amp; LegalTech">Legal &amp; LegalTech</option>
        <option value="Marketing &amp; AdTech">Marketing &amp; AdTech</option>
        <option value="Logistics &amp; Supply Chain">Logistics &amp; Supply Chain</option>
        <option value="Manufacturing &amp; Industry">Manufacturing &amp; Industry</option>
        <option value="SaaS &amp; Cloud">SaaS &amp; Cloud</option>
        <option value="Custom">Custom (type below)</option>
      </select>
    </div>
    <div id="custom-sector-wrap" style="display:none">
      <label>Custom Sector</label>
      <input type="text" id="cfg-sector-custom" placeholder="e.g. AgriTech, CleanEnergy…" maxlength="60"/>
    </div>
    <div>
      <label>SDR Agent Name</label>
      <input type="text" id="cfg-agent" placeholder="e.g. Alex, Priya, Jordan…" maxlength="40"/>
    </div>
    <button class="modal-btn" id="start-btn">🚀 Start Intake Session</button>
    <div class="modal-hint">These settings only affect the AI persona — not the UI.</div>
  </div>
</div>

<!-- ── Header ────────────────────────────────────────────── -->
<header>
  <div class="logo" id="header-logo">?</div>
  <div class="header-text">
    <h1 id="header-company">Lead Intake Agent</h1>
    <div class="sub" id="header-sub">Powered by ScopeSynth</div>
  </div>
  <div class="header-right">
    <span class="sector-pill" id="sector-pill">—</span>
    <span class="badge">🤖 Gemini 2.5 Flash</span>
    <button class="config-btn" id="reconfig-btn" onclick="showConfig()">⚙️ Reconfigure</button>
  </div>
</header>

<!-- ── Chat ──────────────────────────────────────────────── -->
<div id="chat"></div>

<!-- ── Input ─────────────────────────────────────────────── -->
<div class="chat-footer">
  <input id="msg-input" type="text" placeholder="Type your message…" autocomplete="off" disabled/>
  <button id="send-btn" disabled>Send</button>
</div>

<script>
/* ── Config & Session State ────────────────────── */
let company    = '';
let sector     = '';
let agentName  = '';
let sessionId  = Math.random().toString(36).substring(2);
let chatDone   = false;

/* ── URL Param Pre-fill ────────────────────────── */
const params = new URLSearchParams(window.location.search);
const urlCompany = params.get('company') || params.get('Company') || '';
const urlSector  = params.get('sector')  || params.get('Sector')  || '';
const urlAgent   = params.get('agent')   || params.get('Agent')   || '';

if (urlCompany) document.getElementById('cfg-company').value = urlCompany;
if (urlSector)  {
  const sel = document.getElementById('cfg-sector');
  const opt = [...sel.options].find(o => o.value.toLowerCase() === urlSector.toLowerCase());
  if (opt) sel.value = opt.value;
  else {
    sel.value = 'Custom';
    document.getElementById('cfg-sector-custom').value = urlSector;
    document.getElementById('custom-sector-wrap').style.display = '';
  }
}
if (urlAgent) document.getElementById('cfg-agent').value = urlAgent;

/* Auto-start if all three URL params provided */
if (urlCompany && urlSector && urlAgent) {
  setTimeout(() => launchSession(urlCompany, urlSector || 'Technology', urlAgent), 100);
}

/* ── Sector Select Logic ───────────────────────── */
document.getElementById('cfg-sector').addEventListener('change', function() {
  document.getElementById('custom-sector-wrap').style.display =
    this.value === 'Custom' ? '' : 'none';
});

/* ── Show / Hide Config ────────────────────────── */
function showConfig() {
  document.getElementById('config-modal').style.display = 'flex';
}

/* ── Start Button ──────────────────────────────── */
document.getElementById('start-btn').addEventListener('click', () => {
  const co    = document.getElementById('cfg-company').value.trim();
  let   sec   = document.getElementById('cfg-sector').value;
  const cSec  = document.getElementById('cfg-sector-custom').value.trim();
  const ag    = document.getElementById('cfg-agent').value.trim() || 'Alex';

  if (!co) { document.getElementById('cfg-company').focus(); return; }
  if (sec === 'Custom') sec = cSec || 'Technology';
  if (!sec) { document.getElementById('cfg-sector').focus(); return; }

  launchSession(co, sec, ag);
});

function launchSession(co, sec, ag) {
  company   = co;
  sector    = sec;
  agentName = ag;
  sessionId = Math.random().toString(36).substring(2); // fresh session on each launch
  chatDone  = false;

  /* Update header */
  const initials = co.split(/\s+/).map(w => w[0]).join('').toUpperCase().slice(0, 2);
  document.getElementById('header-logo').textContent    = initials;
  document.getElementById('header-company').textContent = co + ' — Lead Intake';
  document.getElementById('header-sub').textContent     = sec;
  document.getElementById('sector-pill').textContent    = '🏭 ' + sec;
  document.title = co + ' — Lead Intake';

  /* Clear chat */
  document.getElementById('chat').innerHTML = '';

  /* Hide modal, enable input */
  document.getElementById('config-modal').style.display = 'none';
  document.getElementById('msg-input').disabled  = false;
  document.getElementById('send-btn').disabled   = false;

  /* Kick off greeting */
  sendMessage(null);
}

/* ── Chat Functions ────────────────────────────── */
const chat     = document.getElementById('chat');
const msgInput = document.getElementById('msg-input');
const sendBtn  = document.getElementById('send-btn');

function addMsg(text, role) {
  const wrap = document.createElement('div');
  wrap.className = `msg ${role}`;
  const av = document.createElement('div');
  av.className = 'avatar';
  av.textContent = role === 'agent' ? agentName.slice(0,2).toUpperCase() : 'You';
  const bub = document.createElement('div');
  bub.className = 'bubble';
  bub.textContent = text;
  wrap.appendChild(av);
  wrap.appendChild(bub);
  chat.appendChild(wrap);
  chat.scrollTop = chat.scrollHeight;
}

function showTyping() {
  const t = document.createElement('div');
  t.className = 'msg agent'; t.id = 'typing-indicator';
  t.innerHTML = `<div class="avatar">${agentName.slice(0,2).toUpperCase()}</div><div class="typing"><span></span><span></span><span></span></div>`;
  chat.appendChild(t);
  chat.scrollTop = chat.scrollHeight;
}

function removeTyping() {
  const t = document.getElementById('typing-indicator');
  if (t) t.remove();
}

async function sendMessage(msg) {
  sendBtn.disabled = true;
  const body = {
    session_id: sessionId,
    company:    company,
    sector:     sector,
    agent_name: agentName,
  };
  if (msg) body.message = msg;

  showTyping();
  try {
    const r    = await fetch('/chat', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body) });
    const data = await r.json();
    removeTyping();
    addMsg(data.response, 'agent');

    if (data.stage === 'done') {
      chatDone = true;
      const banner = document.createElement('div');
      banner.className = 'done-banner';
      banner.textContent = `✅ Lead captured for ${company}! The team will reach out within 24 hours.`;
      chat.appendChild(banner);
      sendBtn.disabled  = true;
      msgInput.disabled = true;
    } else {
      sendBtn.disabled = false;
    }
  } catch(e) {
    removeTyping();
    addMsg('Connection error. Please try again.', 'agent');
    sendBtn.disabled = false;
  }
}

sendBtn.addEventListener('click', () => {
  const txt = msgInput.value.trim();
  if (!txt || chatDone) return;
  addMsg(txt, 'user');
  msgInput.value = '';
  sendMessage(txt);
});

msgInput.addEventListener('keydown', e => {
  if (e.key === 'Enter' && !chatDone) sendBtn.click();
});
</script>
</body>
</html>"""

# ── Routes ────────────────────────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
async def index():
    return HTML_TEMPLATE

@app.post("/chat")
async def chat(payload: dict):
    session_id = payload.get("session_id", str(uuid.uuid4()))
    company    = payload.get("company",    "Our Company").strip() or "Our Company"
    sector     = payload.get("sector",     "Technology").strip()  or "Technology"
    agent_name = payload.get("agent_name", "Alex").strip()        or "Alex"
    user_msg   = payload.get("message")

    response = process_message(session_id, company, sector, agent_name, user_msg)
    state    = sessions.get(session_id, {})

    return {
        "response":  response,
        "stage":     state.get("stage", "unknown"),
        "lead_data": state.get("lead_data", {}),
        "company":   company,
        "sector":    sector,
    }

@app.get("/health")
async def health():
    return {"status": "ok", "sessions": len(sessions)}

if __name__ == "__main__":
    port = int(os.getenv("PORT", 3004))
    logger.info(f"Starting ScopeSynth Lead Intake on port {port}")
    uvicorn.run(app, host="0.0.0.0", port=port)
